theme: jekyll-theme-minimal
title: Junhong's record
description: My portfolio
name : "Ahn Junhong"
urls: 
- text: About me
  url: /about
- text: Portfolio
  url: /portfolio
- text: Algorithm
  url: /algorithm
- blog: Blog
  url: /blog


